sudo: required
language: node_js
node_js:
- "9.11.1"
env:
  global:
    secure: O/LW5ERuTWkUsCBpSCLu+yY7irQnEHsYTNh46x/Rp5dIWThPV7xJMeJjGVno1pN/KbFYpLY2w0mRe1WWr1HH322+7uu8Smvb509hGFcybIE1i2I+vy295+CMc/DrhpgeBSsKziNV0h+sv0x0fjSuILC0CWUB3SQUnkviCPWmfj4SbxLqYVNgvx/W8xjnnqSSBGTcOwZiwioH1XlFuM95gBRjTUnYDoyOh7/Lwo841qWXh6/j7rEFLXDaYD6FpjI3gpRx+jsyc4Nl85cGzBGc7Ecxx0WAgZDfgTmDqpm179io5lqPI8CXvDPuAU8tMNvl97q+1I0Tc0cGIHOnaBhhYueGH/+5QmU/MJdZ5+4H2oawCgbp6qYjO2ZNQYHwYWImOC7ipM81amAz5qsWh2j8G8gRyvD+JwdDD1kUxZ2tAEsOOoTakxtiOqf6e+dxkeMXotn5NSIMl4zJmFgjwyyc+Zr+nu6c0c/YgHqhiTEKJlooPr2KIP0zGceuQtEMsx0J6aAxZVYuulNbg/50o/2ZjU8ruAHk4EbPdK/WbfxtOJwvTbUw4JmV6bCrVKlxPyIxVlZ8MwFSZreUNqaLs0nvIv1nWPKvF9CKzr7XUbT0RkfkhXO+UkglIVBAPZMZKxMyB0FURhF2mHXP+BYxR0ZFRwPK3rMQuewhPJvMB0MIyS8=
deploy:
  provider: npm
  email: jayper@shyft.network
  api_key:
    secure: w72IcgahqGf/y5/c/mi4q8zZxzold1OOpKif1jfpsm7ZYdjXtl1+9c3BHTrUcyEyOBKz9vxmSA9ipgUtE3spUWxf3FCXNaQtQOIoniZhnjLHX48FqPJYRT8K/+jJsSEQr3TL/Hz5pzttQNI0Vx+VCyIoO6iYqUl8dwp8gOq8BAFJcbEEEDnakw+Y7h2xHcRAh0o+3OPiTNkMP2fbvUwanjbRJofaiVQIUEcOnF0hvHLdXfajFex89E9GjJHDd9gVgrkIs+13hUH4T3OmrkZc78YmYH1cJf+aEoNGLsbh/XUWB6U/uvaw6UXtjlCyPzc+WC0DzlNG5/GSGulcIcMVAM6OQovcd+yrpqg7nGjSmwUiWTpa8meaj5C2GnEK10acwdSDbrq4dxFHjfnVVGKlVb72ooL5Xjmpp98XCbGyLWzMPZ0HvOgZQZsqTHMUxgBhVw3EmP/MNK7OtXwtb/RuHr6Px8qxD2VyJ6eD8hapg6iB75XONBHC3IDuBJSDFmPfOGYCTo+/SGUIEzyWvw8phB7wMsQFRML2x37L2fLUgUph8A1hzNuyfjv1+871/JkYgcmT910GKuR2xO0+Pa/e7X7jU8u67xy9T36l0ETuV3KRtabCgYYzNyHnzbn2ot6xoLrRKg4I0hUSi9rRLbA4/j/0h+UrAM8Ka0YHZbHbk4U=
  on:
    repo: ShyftNetwork/shyft_ganache-cli
    branch: jay_travis_shyft_ganache-cli
